baseurl = "/"
title = "The Basic Formal Ontology"
templates = "templates"
assets = "static"

[ontology]
iri = "http://purl.obolibrary.org/obo/"
suffix = "BFO"
source = "test/ontology/bfo.owx"

[build]
output = "./public"
render = true
