baseurl = "http://127.0.0.1:57391/"
title = "The Charging Infrastructure Ontology"
[ontology]
iri = "http://openenergy-platform.org/ontology/chio/"
suffix = "CHIO"
source = "ontology/chio-full.owx"

[build]
render = true

[[import]]
iri = "http://purl.obolibrary.org/obo/"
suffix = "OBO"

[[import]]
iri = "https://www.commoncoreontologies.org/"
suffix = "CCO"
