baseurl = "https://github.com/enioarz/ontology-server"
title = "The Basic Formal Ontology"
templates = "templates"

[ontology]
iri = "http://purl.obolibrary.org/obo/"
suffix = "BFO"
source = "test/ontology/bfo.owx"

[build]
render = true
